import { NextRequest, NextResponse } from "next/server";
import { connectToDatabase } from "@/lib/mongodb";
import { syncAllBrokerageIncome } from "@/lib/brokerageIncome";

// GET /api/income
export async function GET(request: NextRequest) {
  try {
    const models = await connectToDatabase();
    const { Income } = models;
    // This also backfills existing trades and generated monthly invoices.
    await syncAllBrokerageIncome(models);
    const { searchParams } = new URL(request.url);

    const sortField = searchParams.get("sortField") || "createdAt";
    const sortOrder = searchParams.get("sortOrder") || "desc";
    const page = Math.max(1, parseInt(searchParams.get("page") || "1"));
    const pageSize = Math.min(100, Math.max(1, parseInt(searchParams.get("pageSize") || "25")));

    const filterDate = searchParams.get("filterDate") || "";
    const filterInvoiceNo = searchParams.get("filterInvoiceNo") || "";
    const filterCustomer = searchParams.get("filterCustomer") || "";
    const filterCategory = searchParams.get("filterCategory") || "";
    const filterRefNo = searchParams.get("filterRefNo") || "";
    const filterMethod = searchParams.get("filterMethod") || "";

    const query: any = {};

    if (filterInvoiceNo) {
      const n = parseInt(filterInvoiceNo);
      if (!isNaN(n)) query.invoiceNumber = n;
    }
    if (filterCustomer) query.customer = { $regex: filterCustomer, $options: "i" };
    if (filterCategory) query.category = { $regex: filterCategory, $options: "i" };
    if (filterRefNo) {
      // search across all paymentRows.transactionRefNo
      query["paymentRows.transactionRefNo"] = { $regex: filterRefNo, $options: "i" };
    }
    if (filterMethod) {
      query["paymentRows.paymentMethod"] = { $regex: filterMethod, $options: "i" };
    }
    if (filterDate) {
      const d = new Date(filterDate);
      if (!isNaN(d.getTime())) {
        const next = new Date(d);
        next.setDate(next.getDate() + 1);
        query.invoiceDate = {
          $gte: d.toISOString().split("T")[0],
          $lt: next.toISOString().split("T")[0],
        };
      }
    }

    const sortObj: any = {};
    sortObj[sortField] = sortOrder === "asc" ? 1 : -1;

    const total = await Income.countDocuments(query);
    const incomes = await Income.find(query)
      .sort(sortObj)
      .skip((page - 1) * pageSize)
      .limit(pageSize)
      .lean();

    return NextResponse.json({ incomes, total, page, pageSize }, { status: 200 });
  } catch (error: any) {
    console.error("Error fetching income:", error);
    return NextResponse.json({ error: "Failed to fetch income" }, { status: 500 });
  }
}

// POST /api/income
export async function POST(request: NextRequest) {
  try {
    const { Income } = await connectToDatabase();
    const body = await request.json();
    delete body.sourceType;
    delete body.sourceId;
    delete body.sourceKey;
    delete body.isAutoGenerated;
    delete body.tradeNumber;

    // Auto-assign next invoice number if not provided
    if (!body.invoiceNumber) {
      const last = await Income.findOne({}).sort({ invoiceNumber: -1 }).lean() as any;
      body.invoiceNumber = last ? (last.invoiceNumber || 0) + 1 : 1;
    }

    const income = await Income.create(body);
    return NextResponse.json({ income }, { status: 201 });
  } catch (error: any) {
    console.error("Error creating income:", error);
    if (error.name === "ValidationError") {
      return NextResponse.json({ error: error.message }, { status: 400 });
    }
    return NextResponse.json({ error: "Failed to create income" }, { status: 500 });
  }
}
