import type { DatabaseModels } from "@/lib/mongodb";

type BrokerageIncomeModels = Pick<
  DatabaseModels,
  "Agent" | "Category" | "Income" | "MonthlyCollection" | "MonthlyTenant" | "Trade"
>;

interface TradeAgentSource {
  agentId?: unknown;
  agentName?: string;
}

interface ReceiptSource {
  receiptDate?: Date | string | null;
  receiptType?: string;
  note?: string;
}

interface TradeSource {
  _id: unknown;
  tradeNumber?: number;
  agreementStatus?: string;
  tradeType?: string;
  ourRole?: string;
  street?: string;
  city?: string;
  province?: string;
  postalCode?: string;
  completionDate?: Date | string | null;
  firmDate?: Date | string | null;
  offerDate?: Date | string | null;
  basePrice?: number;
  commissionAmount?: number;
  tax?: number;
  agents?: TradeAgentSource[];
  otherBrokerages?: Array<{
    brokerageName?: string;
    agentName?: string;
    phone?: string;
    email?: string;
  }>;
  receipts?: ReceiptSource[];
}

interface AgentSource {
  _id: unknown;
  firstName?: string;
  middleName?: string;
  lastName?: string;
  officeNickName?: string;
  email?: string;
  cellPhone?: string;
  hst?: string;
  street?: string;
  city?: string;
  province?: string;
  postalCode?: string;
  brokerageSharePercent?: string;
  brokerageShareDollar?: string;
}

interface MonthlySource {
  _id?: unknown;
  sourceType: "agent" | "tenant";
  sourceId: string;
  category: "Desk Fee" | "Rent Receivables";
  month: string;
  netAmount?: number;
  hst?: number;
  grossAmount?: number;
  paymentMethod?: string;
  referenceNo?: string;
  receiptDate?: string;
  invoiceNo?: number | null;
}

interface GeneratedIncome {
  sourceType: "trade" | "monthly_collection";
  sourceId: string;
  sourceKey: string;
  isAutoGenerated: true;
  tradeNumber?: number;
  invoiceNumber?: number;
  invoiceDate: string;
  category: string;
  customer: string;
  customerNickName: string;
  address: string;
  hstNumber: string;
  phone: string;
  email: string;
  invoiceItems: Array<{
    item: string;
    price: number;
    quantity: number;
    amount: number;
    hstAmount: number;
  }>;
  subtotal: number;
  hstAmount: number;
  hstExempted: boolean;
  amount: number;
  paymentRows: Array<{
    description: string;
    paymentDate: string;
    paymentMethod: string;
    transactionRefNo: string;
  }>;
}

const roundMoney = (value: number) => Math.round((value + Number.EPSILON) * 100) / 100;

const moneyNumber = (value: unknown) => {
  const parsed = Number(String(value ?? "0").replace(/[^0-9.-]/g, ""));
  return Number.isFinite(parsed) ? parsed : 0;
};

const dateKey = (value: unknown) => {
  if (!value) return "";
  const date = value instanceof Date ? value : new Date(String(value));
  return Number.isNaN(date.getTime()) ? String(value).slice(0, 10) : date.toISOString().slice(0, 10);
};

const fullName = (agent: AgentSource) =>
  agent.officeNickName || [agent.firstName, agent.middleName, agent.lastName].filter(Boolean).join(" ");

const addressFor = (source: Record<string, unknown>) =>
  [source.street, source.city, source.province, source.postalCode].filter(Boolean).join(", ");

const categoryNames = ["Desk Fee", "Split Fee", "Commission Income", "Referral Fees"];

async function ensureIncomeCategories(models: BrokerageIncomeModels) {
  await models.Category.bulkWrite(categoryNames.map((name) => ({
    updateOne: {
      filter: { name },
      update: { $set: { type: "INCOME" }, $setOnInsert: { name } },
      upsert: true,
    },
  })));
}

async function upsertGeneratedIncome(
  models: BrokerageIncomeModels,
  desired: GeneratedIncome[],
  cleanupFilter?: Record<string, unknown>
) {
  const desiredKeys = desired.map((record) => record.sourceKey);
  const existing = desiredKeys.length
    ? await models.Income.find({ sourceKey: { $in: desiredKeys } }).select({ sourceKey: 1 }).lean()
    : [];
  const existingKeys = new Set(existing.map((record) => String(record.sourceKey)));
  const last = await models.Income.findOne({}).sort({ invoiceNumber: -1 }).select({ invoiceNumber: 1 }).lean() as { invoiceNumber?: number } | null;
  let nextInvoice = Number(last?.invoiceNumber || 0) + 1;

  if (desired.length) {
    await models.Income.bulkWrite(desired.map((record) => {
      const { invoiceNumber, ...fields } = record;
      return {
        updateOne: {
          filter: { sourceKey: record.sourceKey },
          update: invoiceNumber
            ? { $set: { ...fields, invoiceNumber } }
            : { $set: fields, $setOnInsert: { invoiceNumber: nextInvoice++ } },
          upsert: true,
        },
      };
    }));
  }

  if (cleanupFilter) {
    const staleFilter = desiredKeys.length
      ? { ...cleanupFilter, sourceKey: { $nin: desiredKeys } }
      : cleanupFilter;
    await models.Income.deleteMany(staleFilter);
  }

  return { created: desiredKeys.filter((key) => !existingKeys.has(key)).length, total: desired.length };
}

function tradeIncomeRecord(
  trade: TradeSource,
  keySuffix: string,
  category: "Split Fee" | "Commission Income" | "Referral Fees",
  netAmount: number,
  customer: Partial<AgentSource> & Record<string, unknown>,
  itemDescription: string
): GeneratedIncome {
  const taxRate = Math.max(0, Number(trade.tax || 0)) / 100;
  const subtotal = roundMoney(netAmount);
  const hstAmount = roundMoney(subtotal * taxRate);
  const sourceId = String(trade._id);
  const firstOtherBrokerage = trade.otherBrokerages?.[0];
  const invoiceDate = dateKey(trade.completionDate || trade.firmDate || trade.offerDate) || new Date().toISOString().slice(0, 10);
  const paymentRows = (trade.receipts || [])
    .filter((receipt) => receipt.receiptDate || receipt.receiptType || receipt.note)
    .map((receipt) => ({
      description: receipt.note || `${category} received for trade #${trade.tradeNumber || ""}`,
      paymentDate: dateKey(receipt.receiptDate),
      paymentMethod: receipt.receiptType || "",
      transactionRefNo: "",
    }));

  return {
    sourceType: "trade",
    sourceId,
    sourceKey: `trade:${sourceId}:${keySuffix}`,
    isAutoGenerated: true,
    tradeNumber: trade.tradeNumber,
    invoiceDate,
    category,
    customer: String(customer.name || fullName(customer as AgentSource) || firstOtherBrokerage?.brokerageName || `Trade #${trade.tradeNumber || ""}`),
    customerNickName: String(customer.officeNickName || customer.agentName || ""),
    address: addressFor(Object.keys(customer).length ? customer : trade as unknown as Record<string, unknown>) || addressFor(trade as unknown as Record<string, unknown>),
    hstNumber: String(customer.hst || ""),
    phone: String(customer.cellPhone || customer.phone || firstOtherBrokerage?.phone || ""),
    email: String(customer.email || firstOtherBrokerage?.email || ""),
    invoiceItems: [{ item: itemDescription, price: subtotal, quantity: 1, amount: subtotal, hstAmount }],
    subtotal,
    hstAmount,
    hstExempted: hstAmount === 0,
    amount: roundMoney(subtotal + hstAmount),
    paymentRows,
  };
}

function deriveTradeIncome(trade: TradeSource, agentsById: Map<string, AgentSource>) {
  if (/collapsed/i.test(trade.agreementStatus || "")) return [];
  const taxRate = Math.max(0, Number(trade.tax || 0)) / 100;
  const netCommission = roundMoney(Number(trade.basePrice || 0) || Number(trade.commissionAmount || 0) / (1 + taxRate));
  if (netCommission <= 0) return [];

  const isReferral = /referral/i.test(`${trade.tradeType || ""} ${trade.ourRole || ""}`);
  if (isReferral) {
    return [tradeIncomeRecord(
      trade,
      "referral",
      "Referral Fees",
      netCommission,
      { name: trade.otherBrokerages?.[0]?.brokerageName || `Trade #${trade.tradeNumber || ""}` },
      `Referral fee - Trade #${trade.tradeNumber || ""}`
    )];
  }

  const assignedAgents = (trade.agents || [])
    .map((tradeAgent) => ({ tradeAgent, agent: agentsById.get(String(tradeAgent.agentId || "")) }))
    .filter((entry): entry is { tradeAgent: TradeAgentSource; agent: AgentSource } => Boolean(entry.agent));

  if (assignedAgents.length) {
    const commissionPerAgent = netCommission / assignedAgents.length;
    const splitRecords = assignedAgents.flatMap(({ tradeAgent, agent }) => {
      const flatShare = moneyNumber(agent.brokerageShareDollar);
      const percentage = moneyNumber(agent.brokerageSharePercent);
      const splitAmount = roundMoney(flatShare > 0 ? flatShare : commissionPerAgent * percentage / 100);
      if (splitAmount <= 0) return [];
      const agentName = fullName(agent) || tradeAgent.agentName || "Agent";
      return [tradeIncomeRecord(
        trade,
        `split:${String(agent._id)}`,
        "Split Fee",
        splitAmount,
        { ...agent, name: agentName },
        `Brokerage split - ${agentName} - Trade #${trade.tradeNumber || ""}`
      )];
    });
    if (splitRecords.length) return splitRecords;
  }

  const brokerage = trade.otherBrokerages?.[0];
  return [tradeIncomeRecord(
    trade,
    "commission",
    "Commission Income",
    netCommission,
    { name: brokerage?.brokerageName || `Trade #${trade.tradeNumber || ""}`, ...brokerage },
    `Commission income - Trade #${trade.tradeNumber || ""}`
  )];
}

function monthlyIncomeRecord(row: MonthlySource, name: string): GeneratedIncome {
  const subtotal = roundMoney(Number(row.netAmount || 0));
  const hstAmount = roundMoney(Number(row.hst || 0));
  const grossAmount = roundMoney(Number(row.grossAmount ?? subtotal + hstAmount));
  const sourceId = String(row._id || row.sourceId);
  return {
    sourceType: "monthly_collection",
    sourceId,
    sourceKey: `monthly:${row.category}:${row.sourceType}:${row.sourceId}:${row.month}`,
    isAutoGenerated: true,
    invoiceNumber: Number(row.invoiceNo),
    invoiceDate: row.receiptDate || `${row.month}-01`,
    category: row.category,
    customer: name,
    customerNickName: "",
    address: "",
    hstNumber: "",
    phone: "",
    email: "",
    invoiceItems: [{ item: `${row.category} - ${row.month}`, price: subtotal, quantity: 1, amount: subtotal, hstAmount }],
    subtotal,
    hstAmount,
    hstExempted: hstAmount === 0,
    amount: grossAmount,
    paymentRows: row.receiptDate || row.paymentMethod || row.referenceNo ? [{
      description: `${row.category} payment - ${row.month}`,
      paymentDate: row.receiptDate || "",
      paymentMethod: row.paymentMethod || "",
      transactionRefNo: row.referenceNo || "",
    }] : [],
  };
}

export async function syncTradeBrokerageIncome(models: BrokerageIncomeModels, tradeDocument: unknown) {
  await ensureIncomeCategories(models);
  const trade = tradeDocument as TradeSource;
  const agentIds = (trade.agents || []).map((agent) => agent.agentId).filter(Boolean);
  const agents = agentIds.length
    ? await models.Agent.find({ _id: { $in: agentIds } }).lean() as unknown as AgentSource[]
    : [];
  const agentsById = new Map(agents.map((agent) => [String(agent._id), agent]));
  return upsertGeneratedIncome(
    models,
    deriveTradeIncome(trade, agentsById),
    { sourceType: "trade", sourceId: String(trade._id) }
  );
}

export async function syncMonthlyBrokerageIncome(
  models: BrokerageIncomeModels,
  rows: Array<MonthlySource & { name?: string }>
) {
  await ensureIncomeCategories(models);
  const clearedKeys = rows
    .filter((row) => Number(row.invoiceNo) <= 0)
    .map((row) => `monthly:${row.category}:${row.sourceType}:${row.sourceId}:${row.month}`);
  if (clearedKeys.length) {
    await models.Income.deleteMany({ sourceType: "monthly_collection", sourceKey: { $in: clearedKeys } });
  }
  const desired = rows
    .filter((row) => Number(row.invoiceNo) > 0)
    .map((row) => monthlyIncomeRecord(row, row.name || `${row.category} customer`));
  return upsertGeneratedIncome(models, desired);
}

export async function syncAllBrokerageIncome(models: BrokerageIncomeModels) {
  await ensureIncomeCategories(models);
  const [trades, agents, collections, tenants] = await Promise.all([
    models.Trade.find({ isActive: { $ne: false } }).lean() as unknown as Promise<TradeSource[]>,
    models.Agent.find({}).lean() as unknown as Promise<AgentSource[]>,
    models.MonthlyCollection.find({ invoiceNo: { $ne: null } }).lean() as unknown as Promise<MonthlySource[]>,
    models.MonthlyTenant.find({}).lean() as unknown as Promise<Array<{ _id: unknown; tenantName?: string; additionalName?: string }>>,
  ]);
  const agentsById = new Map(agents.map((agent) => [String(agent._id), agent]));
  const tenantsById = new Map(tenants.map((tenant) => [
    String(tenant._id),
    [tenant.tenantName, tenant.additionalName].filter(Boolean).join(" / "),
  ]));
  const tradeRecords = trades.flatMap((trade) => deriveTradeIncome(trade, agentsById));
  const monthlyRecords = collections.map((row) => monthlyIncomeRecord(
    row,
    row.sourceType === "agent"
      ? fullName(agentsById.get(row.sourceId) || { _id: row.sourceId }) || "Agent"
      : tenantsById.get(row.sourceId) || "Tenant"
  ));

  await upsertGeneratedIncome(models, tradeRecords, { sourceType: "trade" });
  await upsertGeneratedIncome(models, monthlyRecords, { sourceType: "monthly_collection" });
}
