import { NextRequest, NextResponse } from "next/server";
import { connectToDatabase } from "@/lib/mongodb";

export async function GET(
  _request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { Income } = await connectToDatabase();
    const { id } = await params;
    const income = await Income.findById(id).lean();
    if (!income) return NextResponse.json({ error: "Income not found" }, { status: 404 });
    return NextResponse.json({ income }, { status: 200 });
  } catch (error: any) {
    return NextResponse.json({ error: "Failed to fetch income" }, { status: 500 });
  }
}

export async function PUT(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { Income } = await connectToDatabase();
    const { id } = await params;
    const body = await request.json();
    const existing = await Income.findById(id).select({ isAutoGenerated: 1 }).lean();
    if (!existing) return NextResponse.json({ error: "Income not found" }, { status: 404 });
    if (existing.isAutoGenerated) {
      return NextResponse.json(
        { error: "Automatic income must be changed from its trade or monthly payment." },
        { status: 409 }
      );
    }
    const income = await Income.findByIdAndUpdate(id, body, {
      new: true,
      runValidators: true,
    }).lean();
    if (!income) return NextResponse.json({ error: "Income not found" }, { status: 404 });
    return NextResponse.json({ income }, { status: 200 });
  } catch (error: any) {
    if (error.name === "ValidationError")
      return NextResponse.json({ error: error.message }, { status: 400 });
    return NextResponse.json({ error: "Failed to update income" }, { status: 500 });
  }
}

export async function DELETE(
  _request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { Income } = await connectToDatabase();
    const { id } = await params;
    const existing = await Income.findById(id).select({ isAutoGenerated: 1 }).lean();
    if (!existing) return NextResponse.json({ error: "Income not found" }, { status: 404 });
    if (existing.isAutoGenerated) {
      return NextResponse.json(
        { error: "Automatic income is removed when its trade or monthly payment is removed." },
        { status: 409 }
      );
    }
    const income = await Income.findByIdAndDelete(id);
    if (!income) return NextResponse.json({ error: "Income not found" }, { status: 404 });
    return NextResponse.json({ message: "Income deleted successfully" }, { status: 200 });
  } catch (error: any) {
    return NextResponse.json({ error: "Failed to delete income" }, { status: 500 });
  }
}
