import { Schema, model, models } from "mongoose";

const AgentSchema = new Schema(
  {
    firstName: { type: String, required: true, trim: true },
    middleName: { type: String, trim: true, default: "" },
    lastName: { type: String, required: true, trim: true },
    officeNickName: { type: String, trim: true, default: "" },
    tradeName: { type: String, trim: true, default: "" },
    dateOfBirth: { type: Date, default: null },
    hst: { type: String, trim: true, default: "" },
    sin: { type: String, trim: true, default: "" },
    street: { type: String, trim: true, default: "" },
    city: { type: String, trim: true, default: "" },
    province: { type: String, trim: true, default: "ONT" },
    postalCode: { type: String, trim: true, default: "" },
    email: { type: String, required: true, trim: true, lowercase: true },
    password: { type: String, select: false, default: "" },
    approvalStatus: {
      type: String,
      enum: ["approved", "pending", "rejected"],
      default: "approved",
      index: true,
    },
    registeredByAgent: { type: Boolean, default: false },
    reviewedAt: { type: Date, default: null },
    cellPhone: { type: String, trim: true, default: "" },
    homePhone: { type: String, trim: true, default: "" },
    website: { type: String, trim: true, default: "" },
    agentType: {
      type: String,
      required: true,
      enum: ["Agent", "Broker"],
      default: "Agent",
    },
    agentMentor: { type: String, trim: true, default: "" },
    payToPrec: { type: Boolean, default: false },
    addressIsSameAsAbove: { type: Boolean, default: false },
    precName: { type: String, trim: true, default: "" },
    precStreet: { type: String, trim: true, default: "" },
    precCity: { type: String, trim: true, default: "" },
    precProvince: { type: String, trim: true, default: "ONT" },
    precPostalCode: { type: String, trim: true, default: "" },
    precHst: { type: String, trim: true, default: "" },
    precBusinessNumber: { type: String, trim: true, default: "" },
    photo: { type: String, default: "" },
    recoNumber: { type: String, trim: true, default: "" },
    recoLicExpiry: { type: Date, default: null },
    agentCode: { type: String, trim: true, default: "" },
    isActive: { type: Boolean, default: true },

    startDate: { type: Date, default: null },
    contractAnniversaryDate: { type: Date, default: null },
    terminationDate: { type: Date, default: null },
    recoLicenseNo: { type: String, trim: true, default: "" },
    recoLicenseExpiryDate: { type: Date, default: null },
    boardRows: {
      type: [{ board: { type: String, default: "" }, membershipNo: { type: String, default: "" } }],
      default: [],
    },

    personalBank: { type: String, trim: true, default: "" },
    personalInstituteNo: { type: String, trim: true, default: "" },
    personalTransitNo: { type: String, trim: true, default: "" },
    personalAccountNo: { type: String, trim: true, default: "" },
    precBank: { type: String, trim: true, default: "" },
    precInstituteNo: { type: String, trim: true, default: "" },
    precTransitNo: { type: String, trim: true, default: "" },
    precAccountNo: { type: String, trim: true, default: "" },

    brokerageSharePercent: { type: String, trim: true, default: "10.00" },
    brokerageShareDollar: { type: String, trim: true, default: "$0.00" },
    perTransactionDollar: { type: String, trim: true, default: "$0.00" },
    transactionFeeFirstOnly: { type: String, trim: true, default: "" },
    commissionFrom: { type: String, trim: true, default: "06-May" },
    commissionTo: { type: String, trim: true, default: "31-Dec" },
    afterThatPercent: { type: String, trim: true, default: "" },
    afterThatDollar: { type: String, trim: true, default: "" },
    maxToBrokerage: { type: String, trim: true, default: "$0.00" },
    franchiseFeePercent: { type: String, trim: true, default: "" },
    franchiseFeeMax: { type: String, trim: true, default: "" },
    deskFeeHstPerMonth: { type: String, trim: true, default: "$0.00" },
    deskFeeStartDate: { type: Date, default: null },
    deskFeeOption: { type: String, trim: true, default: "agent_pay" },
    commissionNote: { type: String, default: "" },
    deductions: {
      type: [{
        id: { type: String, default: "" },
        deductionType: { type: String, default: "" },
        amount: { type: String, default: "$0.00" },
        deductionPercent: { type: String, default: "0.00" },
        date: { type: Date, default: null },
        deductionStartDate: { type: Date, default: null },
        note: { type: String, default: "" },
        isActive: { type: Boolean, default: true },
        accountReferenceNo: { type: String, default: "" },
        payableTo: { type: String, default: "" },
        isActive2: { type: Boolean, default: true },
      }],
      default: [],
    },
    documents: {
      type: [{
        id: { type: String, default: "" },
        name: { type: String, default: "" },
        category: { type: String, default: "Other" },
        note: { type: String, default: "" },
        fileName: { type: String, default: "" },
        mimeType: { type: String, default: "application/octet-stream" },
        size: { type: Number, default: 0 },
        dataUrl: { type: String, default: "" },
        uploadedAt: { type: Date, default: Date.now },
      }],
      default: [],
    },
  },
  { timestamps: true }
);

export const Agent = models.Agent || model("Agent", AgentSchema);
export default Agent;
