import { Schema, model, models } from "mongoose";

// Sub-schema for individual invoice line items
const InvoiceItemSchema = new Schema(
  {
    item: { type: String, trim: true, default: "" },
    price: { type: Number, default: 0 },
    quantity: { type: Number, default: 1 },
    amount: { type: Number, default: 0 },
    hstAmount: { type: Number, default: 0 },
  },
  { _id: true }
);

// Sub-schema for payment rows (the + button at the bottom)
const PaymentRowSchema = new Schema(
  {
    description: { type: String, trim: true, default: "" },
    paymentDate: { type: String, trim: true, default: "" },
    paymentMethod: { type: String, trim: true, default: "" },
    transactionRefNo: { type: String, trim: true, default: "" },
  },
  { _id: true }
);

const IncomeSchema = new Schema(
  {
    // Manual entries have no source key. Automatically generated entries use
    // this stable key so changes to a trade/monthly charge update the same row.
    sourceType: {
      type: String,
      enum: ["trade", "monthly_collection"],
      default: undefined,
    },
    sourceId: { type: String, trim: true, default: undefined },
    sourceKey: { type: String, trim: true, default: undefined },
    isAutoGenerated: { type: Boolean, default: false },
    tradeNumber: { type: Number, default: undefined },
    invoiceNumber: { type: Number, default: 1 },
    invoiceDate: { type: String, trim: true, default: "" },
    category: { type: String, trim: true, default: "" },

    // Customer info
    customer: { type: String, trim: true, default: "" },
    customerNickName: { type: String, trim: true, default: "" },
    address: { type: String, trim: true, default: "" },
    hstNumber: { type: String, trim: true, default: "" },
    phone: { type: String, trim: true, default: "" },
    email: { type: String, trim: true, default: "" },

    // Invoice items
    invoiceItems: { type: [InvoiceItemSchema], default: [] },

    // Totals
    subtotal: { type: Number, default: 0 },
    hstAmount: { type: Number, default: 0 },
    hstExempted: { type: Boolean, default: false },
    amount: { type: Number, default: 0 },

    // Payment rows (multiple via + button)
    paymentRows: { type: [PaymentRowSchema], default: [] },
  },
  { timestamps: true }
);

IncomeSchema.index({ sourceKey: 1 }, { unique: true, sparse: true });

export const Income = models.Income || model("Income", IncomeSchema);
export default Income;
